BRAKE: !!python/tuple
- !!python/tuple
  - 916
  - 536
- !!python/tuple
  - 975
  - 536
- !!python/tuple
  - 916
  - 619
- !!python/tuple
  - 975
  - 619
BRAKE_WARN: !!python/tuple
- !!python/tuple
  - 1090
  - 524
- !!python/tuple
  - 1145
  - 524
- !!python/tuple
  - 1090
  - 592
- !!python/tuple
  - 1145
  - 592
