BRAKE: !!python/tuple
- !!python/tuple
  - 349
  - 815
- !!python/tuple
  - 408
  - 815
- !!python/tuple
  - 349
  - 898
- !!python/tuple
  - 408
  - 898
BRAKE_WARN: !!python/tuple
- !!python/tuple
  - 298
  - 491
- !!python/tuple
  - 353
  - 491
- !!python/tuple
  - 298
  - 559
- !!python/tuple
  - 353
  - 559
