BRAKE: !!python/tuple
- !!python/tuple
  - 351
  - 815
- !!python/tuple
  - 410
  - 815
- !!python/tuple
  - 351
  - 898
- !!python/tuple
  - 410
  - 898
BRAKE_WARN: !!python/tuple
- !!python/tuple
  - 300
  - 492
- !!python/tuple
  - 355
  - 492
- !!python/tuple
  - 300
  - 560
- !!python/tuple
  - 355
  - 560
